version: "2"
services:
  app:
    build: ./app
    volumes:
      - ./app:/src/app
      - ./app/logs/npm:/home/node/.npm/_logs
    links:
      - redis:redis
    depends_on:
      - redis
    ports:
      - 127.0.0.1:31380:3000
    restart: always
  nuxt:
    build: ./nuxt
    volumes:
      - ./nuxt:/src/app
      - ./nuxt/logs/npm:/home/node/.npm/_logs
    depends_on:
      - app
    ports:
      - 127.0.0.1:31381:3000
    restart: always
  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - ./redis/config/redis.conf:/etc/redis.conf
      - ./redis/data:/var/lib/redis
    command: redis-server /etc/redis.conf